/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rozza.github.io.gradle.scala.multiversion

import org.gradle.api.Property

interface ScalaMultiversionPluginExtension {
    val scalaVersions: Property<List<String>>
}