/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rozza.github.io.gradle.scala.multiversion

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'rozza.github.io.gradle.scala.multiversion.greeting' plugin.
 */
class ScalaMultiversionPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("rozza.github.io.gradle.scala.multiversion.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
